// frontend/src/app/(auth)/login/page.tsx
'use client'; // useStateやuseRouterを使うため

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { signInWithEmailAndPassword } from 'firebase/auth';
import { auth } from '@/app/lib/firebase'; // Firebaseのauthインスタンス
import { AuthHeader } from '@/app/components/AuthHeader'; // 共通ヘッダー

export default function LoginPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const router = useRouter();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError('');

    try {
      // Firebaseのメール・パスワード認証でログイン
      await signInWithEmailAndPassword(auth, email, password);
      // ログイン成功後、トップページに移動
      router.push('/');
    } catch (err) {
      console.error('ログインエラー:', err);
      setError('メールアドレスまたはパスワードが間違っています。');
    }
  };

  return (
    <div className="flex flex-col items-center min-h-screen">
      <AuthHeader />

      {/* フォーム部分 */}
      <main className="w-full max-w-md bg-white text-gray-800 p-10 rounded-lg mt-12 mx-4">
        <h1 className="text-2xl font-bold text-center mb-8">ログイン</h1>

        <form onSubmit={handleSubmit} className="space-y-6">
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="メールアドレス"
            required
            className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-400"
          />
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder="パスワード"
            required
            className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-400"
          />

          <div className="pt-4 flex justify-center">
            <button
              type="submit"
              className="bg-[#7B61FF] text-white font-bold py-3 px-5 rounded-full hover:opacity-90 transition-opacity"
            >
              ログイン
            </button>
          </div>

          {error && (
            <p className="text-red-600 text-center mt-4">{error}</p>
          )}
        </form>
      </main>
    </div>
  );
}

// frontend/app/pages/login.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Form, Field, ErrorMessage } from 'vee-validate';

useHead({
  title: 'ログイン', // このページのタイトルを「ホーム」に設定
});

definePageMeta({
    layout: 'auth',
    middleware: 'auth'
});

const { logIn } = useAuth();
const userStore = useUserStore();
const router = useRouter();
const errorMessage = ref('');

// handleLoginがフォームの値(values)を受け取るように変更
const handleLogin = async (values: any) => {
    try {
        await logIn(values.email, values.password);
        await userStore.fetchUser();
        router.push('/');
    } catch (error: any) {
        console.error('Login failed:', error);
        errorMessage.value = 'メールアドレスまたはパスワードが違います。';
    }
};
</script>

<template>
    <div class="bg-white text-black rounded-lg shadow-xl p-8 w-full max-w-sm">
        <h2 class="text-2xl font-bold text-center mb-6">ログイン</h2>
        <Form @submit="handleLogin">
            <p v-if="errorMessage" class="text-red-500 text-center mb-4">{{ errorMessage }}</p>

            <div class="mb-4">
                <label for="email" class="block mb-2 text-sm font-medium">メールアドレス</label>
                <Field name="email" rules="required|email" v-slot="{ field, errors }">
                    <input v-bind="field" type="email" id="email"
                        class="w-full p-3 border rounded-lg focus:ring-purple-500 focus:border-purple-500"
                        :class="{ 'border-red-500': errors.length > 0 }" />
                </Field>
                <ErrorMessage name="email" class="text-red-500 text-sm mt-1" />
            </div>

            <div class="mb-6">
                <label for="password" class="block mb-2 text-sm font-medium">パスワード</label>
                <Field name="password" rules="required|min:6" v-slot="{ field, errors }">
                    <input v-bind="field" type="password" id="password"
                        class="w-full p-3 border rounded-lg focus:ring-purple-500 focus:border-purple-500"
                        :class="{ 'border-red-500': errors.length > 0 }" />
                </Field>
                <ErrorMessage name="password" class="text-red-500 text-sm mt-1" />
            </div>

            <button type="submit"
                class="w-full bg-purple-600 text-white rounded-lg py-3 font-bold hover:bg-purple-700 transition-colors">
                ログイン
            </button>
        </Form>
    </div>
</template>
