// frontend/src/app/(auth)/register/page.tsx
'use client'; // インタラクティブな機能のため、先頭にこの行が必要です

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { createUserWithEmailAndPassword } from 'firebase/auth';
import { auth } from '@/app/lib/firebase';
import apiClient from '@/app/lib/apiClient'; // ★ axiosの代わりにapiClientをインポート
import { AuthHeader } from '@/app/components/AuthHeader';

export default function RegisterPage() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const router = useRouter();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError('');

    try {
      // ステップ1: Firebaseにユーザーを作成
      const userCredential = await createUserWithEmailAndPassword(auth, email, password);
      const firebaseUser = userCredential.user;

      // ステップ2: バックエンドAPIを呼び出し、DBにユーザーを保存
      // ★ apiClientを使い、emailも送信データに含める
      await apiClient.post('/users', {
        firebase_uid: firebaseUser.uid,
        name: name,
        email: email,
      });

      router.push('/');
    } catch (err: any) {
      console.error("登録エラーの詳細:", err); // デバッグ用にエラーをコンソールに出力
      setError('登録に失敗しました。入力内容を確認してください。');
    }
  };

  return (
    <div className="flex flex-col items-center min-h-screen">
      <AuthHeader />

      {/* フォーム部分 */}
      <main className="w-full max-w-md bg-white text-gray-800 p-10 rounded-lg mt-12 mx-4">
        <h1 className="text-2xl font-bold text-center mb-8">新規登録</h1>

        <form onSubmit={handleSubmit} className="space-y-6">
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="ユーザーネーム"
            required
            className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-400"
          />
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="メールアドレス"
            required
            className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-400"
          />
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder="パスワード"
            required
            className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-400"
          />

          <div className="pt-4 flex justify-center">
            <button
              type="submit"
              className="bg-[#7B61FF] text-white font-bold py-3 px-5 rounded-full hover:opacity-90 transition-opacity"
            >
              新規登録
            </button>
          </div>

          {error && (
            <p className="text-red-600 text-center mt-4">{error}</p>
          )}
        </form>
      </main>
    </div>
  );
}

// frontend/app/pages/register.vue
<script setup lang="ts">
import { Form, Field, ErrorMessage } from 'vee-validate';
import { ref } from 'vue';
const { signUp } = useAuth();
const router = useRouter();
const config = useRuntimeConfig();
const errorMessage = ref('');

useHead({
  title: '登録', // このページのタイトルを「ホーム」に設定
});

definePageMeta({
    layout: 'auth',
    middleware: 'auth'
});

// handleRegisterがフォームの値(values)を受け取るように変更
const handleRegister = async (values: any) => {
    try {
        const userCredential = await signUp(values.email, values.password);

        await $fetch(`${config.public.apiBaseUrl}/users`, {
            method: 'POST',
            body: {
                name: values.username,
                email: values.email,
                firebase_uid: userCredential.user.uid,
            }
        });

        alert('登録が完了しました。ログインしてください。');
        router.push('/login');

    } catch (error: any) {
        console.error('Registration failed:', error);
        errorMessage.value = '登録に失敗しました。入力内容を確認するか、既に使用されているメールアドレスです。';
    }
};
</script>

<template>
    <div class="bg-white text-black rounded-lg shadow-xl p-8 w-full max-w-sm">
        <h2 class="text-2xl font-bold text-center mb-6">新規登録</h2>
        <Form @submit="handleRegister">
            <p v-if="errorMessage" class="text-red-500 text-center mb-4">{{ errorMessage }}</p>

            <div class="mb-4">
                <label for="username" class="block mb-2 text-sm font-medium">ユーザーネーム</label>
                <Field name="username" rules="required|max:20" v-slot="{ field, errors }">
                    <input v-bind="field" type="text" id="username"
                        class="w-full p-3 border rounded-lg focus:ring-purple-500 focus:border-purple-500"
                        :class="{ 'border-red-500': errors.length > 0 }" />
                </Field>
                <ErrorMessage name="username" class="text-red-500 text-sm mt-1" />
            </div>

            <div class="mb-4">
                <label for="email" class="block mb-2 text-sm font-medium">メールアドレス</label>
                <Field name="email" rules="required|email" v-slot="{ field, errors }">
                    <input v-bind="field" type="email" id="email"
                        class="w-full p-3 border rounded-lg focus:ring-purple-500 focus:border-purple-500"
                        :class="{ 'border-red-500': errors.length > 0 }" />
                </Field>
                <ErrorMessage name="email" class="text-red-500 text-sm mt-1" />
            </div>

            <div class="mb-6">
                <label for="password" class="block mb-2 text-sm font-medium">パスワード</label>
                <Field name="password" rules="required" v-slot="{ field, errors }">
                    <input v-bind="field" type="password" id="password"
                        class="w-full p-3 border rounded-lg focus:ring-purple-500 focus:border-purple-500"
                        :class="{ 'border-red-500': errors.length > 0 }" />
                </Field>
                <ErrorMessage name="password" class="text-red-500 text-sm mt-1" />
            </div>

            <button type="submit"
                class="w-full bg-purple-600 text-white rounded-lg py-3 font-bold hover:bg-purple-700 transition-colors">
                新規登録
            </button>
        </Form>
    </div>
</template>
